---
# tasks file for influxdb
- name: Download influxdb
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1_linux_armhf.tar.gz
    dest: /tmp/influxdb.tgz
    checksum: sha256:723c33b4cf7714fc0864d7a91de324e84427a25b1ca44eaa891bef82523e110a


# The archive already has a full tree. meaning /etc /usr and so on are already included
- name: Uncompress influxdb
  unarchive:
    src: /tmp/influxdb.tgz
    dest: /tmp/
    remote_src: true

- name: Create Influxdb user
  user:
    name: influxdb
    system: true

- name: install influxdb
  command: "cp -vrf /tmp/influxdb-1.7.1-1/etc /tmp/influxdb-1.7.1-1/usr /tmp/influxdb-1.7.1-1/var /"
  args:
    creates:
      - /var/lib/influxdb
      - /usr/bin/influxd


- name: Change permissions on influx's data dir
  file:
    path: /var/lib/influxdb
    owner: influxdb
    recurse: true

- name: Install daemon
  systemd:
    name: /usr/lib/influxdb/scripts/influxdb.service
    enabled: true

- name: run daemon
  service:
    name: influxdb.service
    state: started
    enabled: true
