---
# tasks file for thermos
- name: Load modules on boot
  lineinfile:
    path: /etc/modules
    line: "{{item}}"
    state: present
  with_items:
    - w1-gpio
    - w1-therm
  notify: modprobe

- name: Python is installed
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Git is installed
  package:
    name: git
    state: present

- name: Get the code
  git:
    repo: https://github.com/paulollivier/thermos
    dest: /opt/thermos
    version: "{{version}}"
    force: true
  notify: Restart service

- name: Install dependencies
  pip:
    requirements: /opt/thermos/requirements.txt

- name: Copy service file
  copy:
    src: thermostatd.service
    dest: /etc/systemd/system/thermostatd.service

- name: Copy config file
  copy:
    src: /opt/thermos/thermos.sample.toml
    dest: /etc/thermos.toml
    remote_src: true
  notify: Restart service

- name: Create influx database
  influxdb_database:
    hostname: "{{hostvars['influx'].ansible_host}}"
    database_name: thermos

- name: Install & launch thermostat daemon
  systemd:
    name: thermostatd
    state: started
    enabled: true
    force: true
    daemon_reload: true
